#!/usr/bin/env bash
# Verifies the migration history (db/migrations) against db/schema.sql:
#   1. 001..N applied in order (then 006+ applied again: idempotent) == db/schema.sql
#   2. 006+ apply cleanly on the reported production shape (db/snapshots/production_reported_*.sql)
#      and the result contains every table/column the application uses
#   3. legacy data written under 001-005 survives 006 (prices → supplier_offer_snapshot, match_result → identity_match)
# Usage: scripts/db/verify-migrations.sh [--write]   (--write regenerates db/schema.sql from the migrations)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
source scripts/db/pg.sh
WORK="$ROOT/.e2e"; mkdir -p "$WORK"
PORT="${MIGRATION_PG_PORT:-54339}"
DATA="$WORK/pg-migrations"
trap 'pg_stop "$DATA"' EXIT
pg_start "$DATA" "$PORT"

MIGRATIONS=(db/migrations/*.sql)
RECONCILE=()
for f in "${MIGRATIONS[@]}"; do n="$(basename "$f" | cut -d_ -f1)"; [ "$((10#$n))" -ge 6 ] && RECONCILE+=("$f"); done

# Production is migrated with: psql --single-transaction -v ON_ERROR_STOP=1 -f <file>  (all-or-nothing per file).
apply_tx() { psql_db "$PORT" "$1" --single-transaction -f "$2"; }
# Full data image of a database (for "nothing changed" assertions).
data_image() { "$PG_BIN/pg_dump" -h 127.0.0.1 -p "$PORT" -U postgres -d "$1" --data-only --inserts --no-owner | grep -E '^INSERT' | sort | md5sum; }

# 1. history chain
psql_db "$PORT" postgres -c "create database hist"
for f in "${MIGRATIONS[@]}"; do psql_db "$PORT" hist -f "$f"; done
for f in "${RECONCILE[@]}"; do psql_db "$PORT" hist --single-transaction -f "$f"; done
{
  echo "-- GENERATED by scripts/db/verify-migrations.sh --write. Do not edit by hand."
  echo "-- Result of applying db/migrations/*.sql in order. Used by local/CI E2E; production is changed only by migrations."
  echo
  pg_schema_dump "$PORT" hist
  echo "--"
  echo "-- Reference data seeded by migrations (deterministic order)"
  echo "--"
  echo
  psql_db "$PORT" hist -At -c "select format('INSERT INTO public.freshness_policy (metric, max_age_seconds) VALUES (%L, %s);', metric, max_age_seconds) from freshness_policy order by metric"
} > "$WORK/schema.generated.sql"
if [ "${1:-}" = "--write" ]; then
  cp "$WORK/schema.generated.sql" db/schema.sql
  echo "db/schema.sql regenerated"
fi
# Structural comparison: a database built from the migrations vs one loaded from db/schema.sql.
psql_db "$PORT" postgres -c "create database fromschema"
psql_db "$PORT" fromschema -f db/schema.sql -o /dev/null
pg_fingerprint "$PORT" hist > "$WORK/fingerprint.migrations.txt"
pg_fingerprint "$PORT" fromschema > "$WORK/fingerprint.schema.txt"
if ! diff -u "$WORK/fingerprint.schema.txt" "$WORK/fingerprint.migrations.txt" > "$WORK/fingerprint.diff"; then
  head -60 "$WORK/fingerprint.diff"
  echo "FAIL: db/schema.sql differs from the migration chain (run scripts/db/verify-migrations.sh --write)"
  exit 1
fi
echo "  ✓ structure: $(wc -l < "$WORK/fingerprint.migrations.txt") tables/columns/constraints/indexes/triggers/enums/policy rows identical"
echo "  ✓ migrations 001..$(basename "${MIGRATIONS[-1]}" | cut -d_ -f1) (+ 006+ re-applied) == db/schema.sql"

# 2. reported production shape + new migrations
SNAPSHOT="$(ls db/snapshots/production_reported_*.sql | sort | tail -1)"
psql_db "$PORT" postgres -c "create database prod"
psql_db "$PORT" prod -f "$SNAPSHOT"
for f in "${RECONCILE[@]}"; do psql_db "$PORT" prod --single-transaction -f "$f"; done
for f in "${RECONCILE[@]}"; do psql_db "$PORT" prod --single-transaction -f "$f"; done
pg_schema_dump "$PORT" prod > "$WORK/prod.migrated.sql"
SCHEMA_FILE="$WORK/prod.migrated.sql" node --experimental-strip-types --no-warnings scripts/verify-schema-usage.ts
echo "  ✓ 006+ apply twice on $(basename "$SNAPSHOT"); every table/column the app uses exists afterwards"

# 3. legacy data is never merged or deleted automatically: 006 stops and the database is unchanged.
fresh_legacy_db() { # $1 = db name; builds 001..005
  psql_db "$PORT" postgres -c "create database $1"
  for f in "${MIGRATIONS[@]}"; do
    [ "$((10#$(basename "$f" | cut -d_ -f1)))" -ge 6 ] && break
    psql_db "$PORT" "$1" -f "$f"
  done
  psql_db "$PORT" "$1" <<'SQL'
insert into suppliers(id, supplier_key, name) values ('00000000-0000-4000-8000-000000000001', 'legacy', 'Legacy');
insert into supplier_product(id, supplier_id, supplier_product_id) values ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', 'L-1');
insert into supplier_offer(id, supplier_product_id, orderability) values ('00000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000002', 'ORDERABLE');
insert into master_product(id, product_name) values ('00000000-0000-4000-8000-000000000004', 'Legacy master');
insert into match_result(supplier_product_id, master_product_id, confidence, decision)
  values ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000004', 1, 'AUTO_LINK');
SQL
}
expect_stop() { # $1 = db, $2 = setup SQL, $3 = migration, $4 = expected error fragment
  psql_db "$PORT" "$1" -c "$2"
  local before after out
  before="$(data_image "$1")"
  if out="$(apply_tx "$1" "$3" 2>&1)"; then echo "FAIL: $(basename "$3") should have stopped ($2)"; exit 1; fi
  echo "$out" | grep -q "$4" || { echo "FAIL: unexpected error for $(basename "$3"): $out"; exit 1; }
  after="$(data_image "$1")"
  [ "$before" = "$after" ] || { echo "FAIL: $(basename "$3") changed data although it stopped"; exit 1; }
}
M006="db/migrations/006_live_schema_alignment.sql"
M009="$(ls db/migrations/009_*.sql)"
i=0
for setup in \
  "update supplier_product set title = 'Legacy title'" \
  "update supplier_product set fetched_at = '2026-01-01T00:00:00Z'" \
  "update supplier_product set source_updated_at = now()" \
  "update supplier_offer set cost = 1200" \
  "update supplier_offer set shipping_cost = 300" \
  "update supplier_offer set inventory = 0" \
  "update supplier_offer set shipping_verified = true"; do
  i=$((i + 1)); fresh_legacy_db "legacy$i"
  expect_stop "legacy$i" "$setup" "$M006" "MATCHER 006 stopped"
done
echo "  ✓ 006 stops on any legacy value (title, fetched_at, source_updated_at, cost, shipping_cost, inventory=0, shipping_verified) and changes nothing"

# match_result rows survive the rename. (fetched_at is NOT NULL DEFAULT now() in 001, so any legacy row
# carries a fetch time and 006 rightly stops on it — covered above; here it is cleared to isolate the rename.)
fresh_legacy_db legacyok
psql_db "$PORT" legacyok -c "alter table supplier_product alter column fetched_at drop not null; update supplier_product set fetched_at = null"
for f in "${RECONCILE[@]}"; do apply_tx legacyok "$f"; done
RESULT="$(psql_db "$PORT" legacyok -At -c "select concat_ws('|', (select count(*) from identity_match where decision = 'AUTO_LINK'), (select count(*) from supplier_offer), (select count(*) from supplier_product), (select approval_status from master_product), to_regclass('public.match_result') is null)")"
[ "$RESULT" = "1|1|1|APPROVED|t" ] || { echo "FAIL: legacy rows after 006-009: $RESULT"; exit 1; }
echo "  ✓ match_result rows kept as identity_match; supplier/offer/master rows kept; existing masters stay APPROVED"

# Re-applying 006 never rewinds supplier_offer_freshness.updated_at.
psql_db "$PORT" legacyok -c "insert into supplier_offer_freshness(supplier_offer_id, price_observed_at, updated_at) values ('00000000-0000-4000-8000-000000000003', now(), '2030-01-01T00:00:00Z')"
apply_tx legacyok "$M006"
[ "$(psql_db "$PORT" legacyok -At -c "select updated_at = '2030-01-01T00:00:00Z' from supplier_offer_freshness")" = "t" ] || { echo "FAIL: 006 re-run rewrote freshness.updated_at"; exit 1; }
echo "  ✓ re-running 006 leaves supplier_offer_freshness.updated_at untouched"

# 4. production-shape data problems stop the migration with nothing changed.
reset_prod() { # $1 = db
  psql_db "$PORT" postgres -c "create database $1"
  psql_db "$PORT" "$1" -f "$SNAPSHOT"
  psql_db "$PORT" "$1" <<'SQL'
insert into suppliers(id, supplier_key, name) values ('10000000-0000-4000-8000-000000000001', 's', 'S');
insert into supplier_product(id, supplier_id, supplier_product_id, product_name) values ('10000000-0000-4000-8000-000000000002', '10000000-0000-4000-8000-000000000001', 'P-1', 'Item');
SQL
}
reset_prod dup
expect_stop dup "insert into supplier_offer(supplier_product_id, currency, orderability) values ('10000000-0000-4000-8000-000000000002', 'JPY', 'ORDERABLE'), ('10000000-0000-4000-8000-000000000002', 'JPY', 'UNKNOWN')" "$M009" "duplicate supplier_offer rows"
reset_prod setcount
psql_db "$PORT" setcount -c "alter table supplier_product drop constraint supplier_product_set_count_check"
expect_stop setcount "update supplier_product set set_count = 0" "$M006" "supplier_product_set_count_check"
echo "  ✓ duplicate offers → 009 stops (no merge); invalid set_count → 006 stops; data unchanged in both"
# 5. ops scripts: read-only preflight/status, and rollbacks that restore the exact structure or refuse.
preflight() { psql_db "$PORT" "$1" -f db/ops/preflight.sql 2>&1 >/dev/null | grep -oE "PREFLIGHT \| [A-Z]+ .*" || true; }
reset_prod ops
[ -z "$(preflight ops | grep -E '\| (STOP|REVIEW) ')" ] || { preflight ops; echo "FAIL: preflight flags the reported production shape"; exit 1; }
before_image="$(data_image ops)"; preflight ops >/dev/null; [ "$before_image" = "$(data_image ops)" ] || { echo "FAIL: preflight changed data"; exit 1; }
apply_tx ops "$M006"
pg_fingerprint "$PORT" ops > "$WORK/fp.after006.txt"
for f in db/migrations/00{7,8,9}_*.sql; do apply_tx ops "$f"; done
[ "$(psql_db "$PORT" ops -At -f db/ops/migration_status.sql | grep -c '|t|0|')" = "4" ] || { echo "FAIL: migration_status does not report 006-009 applied"; exit 1; }
for f in 009 008 007; do apply_tx ops "db/ops/rollback/${f}_rollback.sql"; done
pg_fingerprint "$PORT" ops > "$WORK/fp.rolledback.txt"
diff -u "$WORK/fp.after006.txt" "$WORK/fp.rolledback.txt" || { echo "FAIL: rollback 009→007 does not restore the post-006 structure"; exit 1; }
for f in db/migrations/00{7,8,9}_*.sql; do apply_tx ops "$f"; done
expect_stop ops "insert into master_product(product_name, status, approval_status, origin) values ('cand', 'INACTIVE', 'CANDIDATE', 'SUPPLIER_CANDIDATE')" db/ops/rollback/007_rollback.sql "ROLLBACK 007 stopped"
expect_stop ops "insert into purchase_review(amount, status, requested_by_email) values (100, 'FAILED', 'buyer@example.com')" db/ops/rollback/008_rollback.sql "ROLLBACK 008 stopped"
reset_prod opsdirty
psql_db "$PORT" opsdirty -c "insert into supplier_offer(supplier_product_id, currency, orderability) values ('10000000-0000-4000-8000-000000000002','JPY','ORDERABLE'),('10000000-0000-4000-8000-000000000002','JPY','UNKNOWN'); alter table supplier_offer add column cost numeric; update supplier_offer set cost = 1"
[ "$(preflight opsdirty | grep -c '| STOP ')" = "2" ] || { preflight opsdirty; echo "FAIL: preflight missed STOP conditions"; exit 1; }
psql_db "$PORT" hist -f db/ops/preflight.sql >/dev/null 2>&1 || { echo "FAIL: preflight errors on the 001-009 shape"; exit 1; }
echo "  ✓ preflight is read-only, clean on the reported production shape, flags duplicates/legacy data as STOP"
echo "  ✓ migration_status reports 006-009; rollback 009→007 restores the post-006 structure; rollbacks refuse to drop data"
echo "MATCHER migration verification: PASS"
