#!/usr/bin/env bash
# Verifies the migration history (db/migrations) against db/schema.sql:
#   1. 001..N applied in order (then 006+ applied again: idempotent) == db/schema.sql
#   2. 006+ apply cleanly on the reported production shape (db/snapshots/production_reported_*.sql)
#      and the result contains every table/column the application uses
#   3. legacy data written under 001-005 survives 006 (prices → supplier_offer_snapshot, match_result → identity_match)
# Usage: scripts/db/verify-migrations.sh [--write]   (--write regenerates db/schema.sql from the migrations)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
source scripts/db/pg.sh
WORK="$ROOT/.e2e"; mkdir -p "$WORK"
PORT="${MIGRATION_PG_PORT:-54339}"
DATA="$WORK/pg-migrations"
trap 'pg_stop "$DATA"' EXIT
pg_start "$DATA" "$PORT"

MIGRATIONS=(db/migrations/*.sql)
RECONCILE=()
for f in "${MIGRATIONS[@]}"; do n="$(basename "$f" | cut -d_ -f1)"; [ "$((10#$n))" -ge 6 ] && RECONCILE+=("$f"); done

# 1. history chain
psql_db "$PORT" postgres -c "create database hist"
for f in "${MIGRATIONS[@]}"; do psql_db "$PORT" hist -f "$f"; done
for f in "${RECONCILE[@]}"; do psql_db "$PORT" hist -f "$f"; done
{
  echo "-- GENERATED by scripts/db/verify-migrations.sh --write. Do not edit by hand."
  echo "-- Result of applying db/migrations/*.sql in order. Used by local/CI E2E; production is changed only by migrations."
  echo
  pg_schema_dump "$PORT" hist
  echo "--"
  echo "-- Reference data seeded by migrations (deterministic order)"
  echo "--"
  echo
  psql_db "$PORT" hist -At -c "select format('INSERT INTO public.freshness_policy (metric, max_age_seconds) VALUES (%L, %s);', metric, max_age_seconds) from freshness_policy order by metric"
} > "$WORK/schema.generated.sql"
if [ "${1:-}" = "--write" ]; then
  cp "$WORK/schema.generated.sql" db/schema.sql
  echo "db/schema.sql regenerated"
fi
# Structural comparison: a database built from the migrations vs one loaded from db/schema.sql.
psql_db "$PORT" postgres -c "create database fromschema"
psql_db "$PORT" fromschema -f db/schema.sql -o /dev/null
pg_fingerprint "$PORT" hist > "$WORK/fingerprint.migrations.txt"
pg_fingerprint "$PORT" fromschema > "$WORK/fingerprint.schema.txt"
if ! diff -u "$WORK/fingerprint.schema.txt" "$WORK/fingerprint.migrations.txt" > "$WORK/fingerprint.diff"; then
  head -60 "$WORK/fingerprint.diff"
  echo "FAIL: db/schema.sql differs from the migration chain (run scripts/db/verify-migrations.sh --write)"
  exit 1
fi
echo "  ✓ structure: $(wc -l < "$WORK/fingerprint.migrations.txt") tables/columns/constraints/indexes/triggers/enums/policy rows identical"
echo "  ✓ migrations 001..$(basename "${MIGRATIONS[-1]}" | cut -d_ -f1) (+ 006+ re-applied) == db/schema.sql"

# 2. reported production shape + new migrations
SNAPSHOT="$(ls db/snapshots/production_reported_*.sql | sort | tail -1)"
psql_db "$PORT" postgres -c "create database prod"
psql_db "$PORT" prod -f "$SNAPSHOT"
for f in "${RECONCILE[@]}"; do psql_db "$PORT" prod -f "$f"; done
for f in "${RECONCILE[@]}"; do psql_db "$PORT" prod -f "$f"; done
pg_schema_dump "$PORT" prod > "$WORK/prod.migrated.sql"
SCHEMA_FILE="$WORK/prod.migrated.sql" node --experimental-strip-types --no-warnings scripts/verify-schema-usage.ts
echo "  ✓ 006+ apply twice on $(basename "$SNAPSHOT"); every table/column the app uses exists afterwards"

# 3. legacy data survives
psql_db "$PORT" postgres -c "create database legacy"
for f in "${MIGRATIONS[@]}"; do
  [ "$((10#$(basename "$f" | cut -d_ -f1)))" -ge 6 ] && break
  psql_db "$PORT" legacy -f "$f"
done
psql_db "$PORT" legacy <<'SQL'
insert into suppliers(id, supplier_key, name) values ('00000000-0000-4000-8000-000000000001', 'legacy', 'Legacy');
insert into supplier_product(id, supplier_id, supplier_product_id, title, fetched_at)
  values ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', 'L-1', 'Legacy title', '2026-01-01T00:00:00Z');
insert into supplier_offer(id, supplier_product_id, cost, shipping_cost, inventory, shipping_verified, observed_at, orderability)
  values ('00000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000002', 1200, 300, 4, true, '2026-01-02T00:00:00Z', 'ORDERABLE');
insert into master_product(id, product_name) values ('00000000-0000-4000-8000-000000000004', 'Legacy master');
insert into match_result(supplier_product_id, master_product_id, confidence, decision)
  values ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000004', 1, 'AUTO_LINK');
SQL
for f in "${RECONCILE[@]}"; do psql_db "$PORT" legacy -f "$f"; done
RESULT="$(psql_db "$PORT" legacy -At <<'SQL'
select concat_ws('|',
  (select product_name from supplier_product),
  (select first_seen_at = '2026-01-01T00:00:00Z' from supplier_product),
  (select concat_ws(',', supplier_cost, shipping_cost, inventory, shipping_confidence, observed_at = '2026-01-02T00:00:00Z') from supplier_offer_snapshot),
  (select count(*) from identity_match where decision = 'AUTO_LINK'),
  (select approval_status from master_product));
SQL
)"
[ "$RESULT" = "Legacy title|t|1200.00,300.00,4,1.0000,t|1|APPROVED" ] || { echo "FAIL: legacy data migration: $RESULT"; exit 1; }
echo "  ✓ legacy data kept: title→product_name, fetched_at→first_seen_at, offer price/stock→snapshot, match_result→identity_match"
echo "MATCHER migration verification: PASS"
