-- GENERATED by scripts/db/verify-migrations.sh --write. Do not edit by hand.
-- Result of applying db/migrations/*.sql in order. Used by local/CI E2E; production is changed only by migrations.

--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'SQL_ASCII';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';

--
-- Name: identity_decision; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.identity_decision AS ENUM (
    'AUTO_LINK',
    'REVIEW',
    'BLOCK',
    'REJECT'
);

--
-- Name: match_decision; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.match_decision AS ENUM (
    'AUTO_LINK',
    'REVIEW',
    'REJECT'
);

--
-- Name: media_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.media_type AS ENUM (
    'IMAGE',
    'SPECIFICATION'
);

--
-- Name: orderability_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.orderability_status AS ENUM (
    'ORDERABLE',
    'OUT_OF_STOCK',
    'UNKNOWN',
    'BLOCKED'
);

--
-- Name: product_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.product_status AS ENUM (
    'ACTIVE',
    'INACTIVE'
);

--
-- Name: quality_run_state; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.quality_run_state AS ENUM (
    'DETECTED',
    'DIAGNOSED',
    'REPAIRED',
    'TESTED',
    'RETESTED',
    'RESOLVED'
);

--
-- Name: sellability_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.sellability_status AS ENUM (
    'SELLABLE',
    'BLOCKED'
);

--
-- Name: prevent_auto_link_hard_block(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.prevent_auto_link_hard_block() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  if new.hard_block and new.decision = 'AUTO_LINK' then
    raise exception 'AUTO_LINK is forbidden when hard_block=true';
  end if;
  return new;
end;
$$;

--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: freshness_policy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.freshness_policy (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    metric text NOT NULL,
    max_age_seconds integer NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT freshness_policy_max_age_seconds_check CHECK ((max_age_seconds > 0)),
    CONSTRAINT freshness_policy_metric_check CHECK ((metric = ANY (ARRAY['PRICE'::text, 'INVENTORY'::text, 'SHIPPING'::text])))
);

--
-- Name: identity_hard_block; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.identity_hard_block (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    match_result_id uuid NOT NULL,
    reason_code text NOT NULL,
    source_value text,
    master_value text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT identity_hard_block_reason_code_check CHECK ((reason_code = ANY (ARRAY['MPN_MISMATCH'::text, 'SET_COUNT_MISMATCH'::text, 'COLOR_MISMATCH'::text, 'SIZE_MISMATCH'::text, 'CONDITION_MISMATCH'::text, 'VARIANT_MISMATCH'::text])))
);

--
-- Name: identity_match; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.identity_match (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplier_product_id uuid NOT NULL,
    master_product_id uuid,
    confidence numeric(5,4) NOT NULL,
    decision public.identity_decision NOT NULL,
    hard_block_reasons jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    hard_block boolean DEFAULT false NOT NULL,
    CONSTRAINT match_result_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)))
);

--
-- Name: ingestion_run; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingestion_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source text NOT NULL,
    status text NOT NULL,
    item_count integer DEFAULT 0 NOT NULL,
    error_count integer DEFAULT 0 NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    CONSTRAINT ingestion_run_error_count_check CHECK ((error_count >= 0)),
    CONSTRAINT ingestion_run_item_count_check CHECK ((item_count >= 0)),
    CONSTRAINT ingestion_run_status_check CHECK ((status = ANY (ARRAY['RUNNING'::text, 'SUCCEEDED'::text, 'FAILED'::text, 'PARTIAL'::text])))
);

--
-- Name: market_price_observation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_price_observation (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    master_product_id uuid NOT NULL,
    product_variant_id uuid,
    source text NOT NULL,
    source_product_id text,
    sale_price numeric(14,2) NOT NULL,
    payment_fee numeric(14,2),
    marketplace_fee numeric(14,2),
    tax numeric(14,2),
    other_cost numeric(14,2),
    sold boolean DEFAULT false NOT NULL,
    source_url text,
    observed_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT market_price_observation_sale_price_check CHECK ((sale_price >= (0)::numeric))
);

--
-- Name: master_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.master_product (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    brand text,
    product_name text NOT NULL,
    manufacturer text,
    model_number text,
    status public.product_status DEFAULT 'ACTIVE'::public.product_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    approval_status text DEFAULT 'APPROVED'::text NOT NULL,
    origin text DEFAULT 'MANUAL'::text NOT NULL,
    origin_supplier_product_id uuid,
    reviewed_at timestamp with time zone,
    reviewed_by text,
    CONSTRAINT master_product_active_requires_approval CHECK (((status <> 'ACTIVE'::public.product_status) OR (approval_status = 'APPROVED'::text))),
    CONSTRAINT master_product_approval_status_check CHECK ((approval_status = ANY (ARRAY['CANDIDATE'::text, 'APPROVED'::text, 'REJECTED'::text]))),
    CONSTRAINT master_product_origin_check CHECK ((origin = ANY (ARRAY['MANUAL'::text, 'SUPPLIER_CANDIDATE'::text])))
);

--
-- Name: match_evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.match_evidence (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    match_result_id uuid NOT NULL,
    field_name text NOT NULL,
    comparison text NOT NULL,
    source_value text,
    master_value text,
    weight numeric(6,4),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: product_identifier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_identifier (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    master_product_id uuid NOT NULL,
    identifier_type text NOT NULL,
    identifier_value text NOT NULL,
    normalized_value text NOT NULL,
    source text,
    is_primary boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT product_identifier_identifier_type_check CHECK ((identifier_type = ANY (ARRAY['JAN'::text, 'EAN'::text, 'UPC'::text, 'MPN'::text, 'SKU'::text, 'SUPPLIER_PRODUCT_NO'::text])))
);

--
-- Name: product_media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_media (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    master_product_id uuid NOT NULL,
    product_variant_id uuid,
    media_type public.media_type NOT NULL,
    media_url text NOT NULL,
    source text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: product_variant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_variant (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    master_product_id uuid NOT NULL,
    variant_key text NOT NULL,
    color text,
    size text,
    capacity text,
    generation text,
    set_count integer,
    condition text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT product_variant_set_count_check CHECK (((set_count IS NULL) OR (set_count > 0)))
);

--
-- Name: profit_snapshot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profit_snapshot (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplier_offer_id uuid NOT NULL,
    sale_price numeric(14,2) NOT NULL,
    supplier_cost numeric(14,2),
    shipping_cost numeric(14,2),
    payment_fee numeric(14,2),
    marketplace_fee numeric(14,2),
    tax numeric(14,2),
    other_cost numeric(14,2),
    expected_profit numeric(14,2),
    calculated_at timestamp with time zone DEFAULT now() NOT NULL,
    cost_complete boolean DEFAULT false NOT NULL,
    CONSTRAINT profit_snapshot_sale_price_check CHECK ((sale_price >= (0)::numeric))
);

--
-- Name: purchase_review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_review (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    master_product_id uuid,
    supplier_offer_id uuid,
    amount bigint NOT NULL,
    currency text DEFAULT 'jpy'::text NOT NULL,
    status text NOT NULL,
    stripe_checkout_session_id text,
    stripe_payment_intent_id text,
    decision_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    rejection_reason text,
    authorized_at timestamp with time zone,
    reviewed_at timestamp with time zone,
    captured_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    requested_by_user_id uuid,
    requested_by_email text,
    verified_terms jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT purchase_review_amount_check CHECK ((amount > 0)),
    CONSTRAINT purchase_review_status_check CHECK ((status = ANY (ARRAY['AUTHORIZING'::text, 'AWAITING_HUMAN'::text, 'APPROVED'::text, 'REJECTED'::text, 'EXPIRED'::text, 'FAILED'::text])))
);

--
-- Name: quality_diagnosis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quality_diagnosis (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    patrol_run_id uuid NOT NULL,
    severity text NOT NULL,
    code text NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT quality_diagnosis_severity_check CHECK ((severity = ANY (ARRAY['INFO'::text, 'WARN'::text, 'ERROR'::text])))
);

--
-- Name: quality_gate_result; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quality_gate_result (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplier_offer_id uuid NOT NULL,
    status public.sellability_status NOT NULL,
    checks jsonb DEFAULT '{}'::jsonb NOT NULL,
    blocking_reasons jsonb DEFAULT '[]'::jsonb NOT NULL,
    evaluated_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: quality_patrol_run; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quality_patrol_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    status text NOT NULL,
    summary jsonb DEFAULT '{}'::jsonb NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    CONSTRAINT quality_patrol_run_status_check CHECK ((status = ANY (ARRAY['RUNNING'::text, 'PASSED'::text, 'FAILED'::text])))
);

--
-- Name: quality_run; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quality_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    state public.quality_run_state NOT NULL,
    target_type text NOT NULL,
    target_id uuid,
    root_cause jsonb DEFAULT '{}'::jsonb NOT NULL,
    repair_action jsonb DEFAULT '{}'::jsonb NOT NULL,
    test_result jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: supplier_offer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supplier_offer (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplier_product_id uuid NOT NULL,
    product_variant_id uuid,
    currency character(3) DEFAULT 'JPY'::bpchar NOT NULL,
    orderability public.orderability_status DEFAULT 'UNKNOWN'::public.orderability_status NOT NULL,
    price_age_seconds integer,
    inventory_age_seconds integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT supplier_offer_inventory_age_seconds_check CHECK (((inventory_age_seconds IS NULL) OR (inventory_age_seconds >= 0))),
    CONSTRAINT supplier_offer_price_age_seconds_check CHECK (((price_age_seconds IS NULL) OR (price_age_seconds >= 0)))
);

--
-- Name: supplier_offer_freshness; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supplier_offer_freshness (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplier_offer_id uuid NOT NULL,
    price_observed_at timestamp with time zone,
    inventory_observed_at timestamp with time zone,
    shipping_observed_at timestamp with time zone,
    checked_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: supplier_offer_observation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supplier_offer_observation (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplier_offer_id uuid NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL,
    price numeric(14,2),
    shipping_cost numeric(14,2),
    inventory integer,
    orderability public.orderability_status,
    price_observed_at timestamp with time zone,
    inventory_observed_at timestamp with time zone,
    shipping_observed_at timestamp with time zone,
    source text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT supplier_offer_observation_inventory_check CHECK (((inventory IS NULL) OR (inventory >= 0))),
    CONSTRAINT supplier_offer_observation_price_check CHECK (((price IS NULL) OR (price >= (0)::numeric))),
    CONSTRAINT supplier_offer_observation_shipping_cost_check CHECK (((shipping_cost IS NULL) OR (shipping_cost >= (0)::numeric)))
);

--
-- Name: supplier_offer_snapshot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supplier_offer_snapshot (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplier_offer_id uuid NOT NULL,
    supplier_cost numeric(14,2),
    shipping_cost numeric(14,2),
    inventory integer,
    shipping_confidence numeric(5,4),
    observed_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT supplier_offer_snapshot_inventory_check CHECK (((inventory IS NULL) OR (inventory >= 0))),
    CONSTRAINT supplier_offer_snapshot_shipping_confidence_check CHECK (((shipping_confidence IS NULL) OR ((shipping_confidence >= (0)::numeric) AND (shipping_confidence <= (1)::numeric)))),
    CONSTRAINT supplier_offer_snapshot_shipping_cost_check CHECK (((shipping_cost IS NULL) OR (shipping_cost >= (0)::numeric))),
    CONSTRAINT supplier_offer_snapshot_supplier_cost_check CHECK (((supplier_cost IS NULL) OR (supplier_cost >= (0)::numeric)))
);

--
-- Name: supplier_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supplier_product (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplier_id uuid NOT NULL,
    supplier_product_id text NOT NULL,
    supplier_sku text,
    brand text,
    model_number text,
    source_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    product_name text,
    manufacturer text,
    color text,
    size text,
    capacity text,
    generation text,
    set_count integer,
    condition text,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT supplier_product_set_count_check CHECK (((set_count IS NULL) OR (set_count > 0)))
);

--
-- Name: supplier_product_identifier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supplier_product_identifier (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplier_product_id uuid NOT NULL,
    identifier_type text NOT NULL,
    identifier_value text NOT NULL,
    normalized_value text NOT NULL,
    source text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT supplier_product_identifier_identifier_type_check CHECK ((identifier_type = ANY (ARRAY['JAN'::text, 'EAN'::text, 'UPC'::text, 'MPN'::text, 'SKU'::text, 'SUPPLIER_PRODUCT_NO'::text])))
);

--
-- Name: suppliers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suppliers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplier_key text NOT NULL,
    name text NOT NULL,
    status public.product_status DEFAULT 'ACTIVE'::public.product_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: freshness_policy freshness_policy_metric_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.freshness_policy
    ADD CONSTRAINT freshness_policy_metric_key UNIQUE (metric);

--
-- Name: freshness_policy freshness_policy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.freshness_policy
    ADD CONSTRAINT freshness_policy_pkey PRIMARY KEY (id);

--
-- Name: identity_hard_block identity_hard_block_match_result_id_reason_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identity_hard_block
    ADD CONSTRAINT identity_hard_block_match_result_id_reason_code_key UNIQUE (match_result_id, reason_code);

--
-- Name: identity_hard_block identity_hard_block_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identity_hard_block
    ADD CONSTRAINT identity_hard_block_pkey PRIMARY KEY (id);

--
-- Name: ingestion_run ingestion_run_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingestion_run
    ADD CONSTRAINT ingestion_run_pkey PRIMARY KEY (id);

--
-- Name: market_price_observation market_price_observation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_price_observation
    ADD CONSTRAINT market_price_observation_pkey PRIMARY KEY (id);

--
-- Name: master_product master_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_product
    ADD CONSTRAINT master_product_pkey PRIMARY KEY (id);

--
-- Name: match_evidence match_evidence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_evidence
    ADD CONSTRAINT match_evidence_pkey PRIMARY KEY (id);

--
-- Name: identity_match match_result_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identity_match
    ADD CONSTRAINT match_result_pkey PRIMARY KEY (id);

--
-- Name: product_identifier product_identifier_master_product_id_identifier_type_normal_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_identifier
    ADD CONSTRAINT product_identifier_master_product_id_identifier_type_normal_key UNIQUE (master_product_id, identifier_type, normalized_value);

--
-- Name: product_identifier product_identifier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_identifier
    ADD CONSTRAINT product_identifier_pkey PRIMARY KEY (id);

--
-- Name: product_media product_media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_media
    ADD CONSTRAINT product_media_pkey PRIMARY KEY (id);

--
-- Name: product_variant product_variant_master_product_id_variant_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variant
    ADD CONSTRAINT product_variant_master_product_id_variant_key_key UNIQUE (master_product_id, variant_key);

--
-- Name: product_variant product_variant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variant
    ADD CONSTRAINT product_variant_pkey PRIMARY KEY (id);

--
-- Name: profit_snapshot profit_snapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profit_snapshot
    ADD CONSTRAINT profit_snapshot_pkey PRIMARY KEY (id);

--
-- Name: purchase_review purchase_review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_review
    ADD CONSTRAINT purchase_review_pkey PRIMARY KEY (id);

--
-- Name: purchase_review purchase_review_stripe_checkout_session_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_review
    ADD CONSTRAINT purchase_review_stripe_checkout_session_id_key UNIQUE (stripe_checkout_session_id);

--
-- Name: purchase_review purchase_review_stripe_payment_intent_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_review
    ADD CONSTRAINT purchase_review_stripe_payment_intent_id_key UNIQUE (stripe_payment_intent_id);

--
-- Name: quality_diagnosis quality_diagnosis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quality_diagnosis
    ADD CONSTRAINT quality_diagnosis_pkey PRIMARY KEY (id);

--
-- Name: quality_gate_result quality_gate_result_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quality_gate_result
    ADD CONSTRAINT quality_gate_result_pkey PRIMARY KEY (id);

--
-- Name: quality_patrol_run quality_patrol_run_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quality_patrol_run
    ADD CONSTRAINT quality_patrol_run_pkey PRIMARY KEY (id);

--
-- Name: quality_run quality_run_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quality_run
    ADD CONSTRAINT quality_run_pkey PRIMARY KEY (id);

--
-- Name: supplier_offer_freshness supplier_offer_freshness_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_offer_freshness
    ADD CONSTRAINT supplier_offer_freshness_pkey PRIMARY KEY (id);

--
-- Name: supplier_offer_freshness supplier_offer_freshness_supplier_offer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_offer_freshness
    ADD CONSTRAINT supplier_offer_freshness_supplier_offer_id_key UNIQUE (supplier_offer_id);

--
-- Name: supplier_offer_observation supplier_offer_observation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_offer_observation
    ADD CONSTRAINT supplier_offer_observation_pkey PRIMARY KEY (id);

--
-- Name: supplier_offer supplier_offer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_offer
    ADD CONSTRAINT supplier_offer_pkey PRIMARY KEY (id);

--
-- Name: supplier_offer_snapshot supplier_offer_snapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_offer_snapshot
    ADD CONSTRAINT supplier_offer_snapshot_pkey PRIMARY KEY (id);

--
-- Name: supplier_product_identifier supplier_product_identifier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_product_identifier
    ADD CONSTRAINT supplier_product_identifier_pkey PRIMARY KEY (id);

--
-- Name: supplier_product_identifier supplier_product_identifier_supplier_product_id_identifier__key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_product_identifier
    ADD CONSTRAINT supplier_product_identifier_supplier_product_id_identifier__key UNIQUE (supplier_product_id, identifier_type, normalized_value);

--
-- Name: supplier_product supplier_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_product
    ADD CONSTRAINT supplier_product_pkey PRIMARY KEY (id);

--
-- Name: supplier_product supplier_product_supplier_id_supplier_product_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_product
    ADD CONSTRAINT supplier_product_supplier_id_supplier_product_id_key UNIQUE (supplier_id, supplier_product_id);

--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);

--
-- Name: suppliers suppliers_supplier_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_supplier_key_key UNIQUE (supplier_key);

--
-- Name: idx_evidence_match; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evidence_match ON public.match_evidence USING btree (match_result_id);

--
-- Name: idx_gate_evaluated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gate_evaluated ON public.quality_gate_result USING btree (evaluated_at DESC);

--
-- Name: idx_gate_offer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gate_offer ON public.quality_gate_result USING btree (supplier_offer_id, evaluated_at DESC);

--
-- Name: idx_identifier_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_identifier_lookup ON public.product_identifier USING btree (identifier_type, normalized_value);

--
-- Name: idx_identity_hard_block_match; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_identity_hard_block_match ON public.identity_hard_block USING btree (match_result_id);

--
-- Name: idx_identity_match_hard_block; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_identity_match_hard_block ON public.identity_match USING btree (hard_block, created_at DESC);

--
-- Name: idx_identity_match_master; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_identity_match_master ON public.identity_match USING btree (master_product_id, created_at DESC);

--
-- Name: idx_identity_match_supplier_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_identity_match_supplier_product ON public.identity_match USING btree (supplier_product_id, created_at DESC);

--
-- Name: idx_market_price_master_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_market_price_master_observed ON public.market_price_observation USING btree (master_product_id, observed_at DESC);

--
-- Name: idx_master_product_approval; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_master_product_approval ON public.master_product USING btree (approval_status, created_at DESC);

--
-- Name: idx_master_product_origin_supplier_product; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_master_product_origin_supplier_product ON public.master_product USING btree (origin_supplier_product_id) WHERE (origin_supplier_product_id IS NOT NULL);

--
-- Name: idx_product_identifier_global_gtin; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_product_identifier_global_gtin ON public.product_identifier USING btree (identifier_type, normalized_value) WHERE (identifier_type = ANY (ARRAY['JAN'::text, 'EAN'::text, 'UPC'::text]));

--
-- Name: idx_product_identifier_product_scoped; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_product_identifier_product_scoped ON public.product_identifier USING btree (master_product_id, identifier_type, normalized_value);

--
-- Name: idx_profit_offer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_profit_offer ON public.profit_snapshot USING btree (supplier_offer_id, calculated_at DESC);

--
-- Name: idx_quality_run_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_quality_run_target ON public.quality_run USING btree (target_type, target_id, created_at DESC);

--
-- Name: idx_supplier_offer_freshness_checked; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_supplier_offer_freshness_checked ON public.supplier_offer_freshness USING btree (checked_at DESC);

--
-- Name: idx_supplier_offer_observation_offer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_supplier_offer_observation_offer ON public.supplier_offer_observation USING btree (supplier_offer_id, observed_at DESC);

--
-- Name: idx_supplier_offer_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_supplier_offer_product ON public.supplier_offer USING btree (supplier_product_id);

--
-- Name: idx_supplier_offer_product_currency; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_supplier_offer_product_currency ON public.supplier_offer USING btree (supplier_product_id, currency);

--
-- Name: idx_supplier_offer_snapshot_offer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_supplier_offer_snapshot_offer ON public.supplier_offer_snapshot USING btree (supplier_offer_id, observed_at DESC);

--
-- Name: idx_supplier_product_identifier_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_supplier_product_identifier_lookup ON public.supplier_product_identifier USING btree (identifier_type, normalized_value);

--
-- Name: idx_supplier_product_last_seen; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_supplier_product_last_seen ON public.supplier_product USING btree (last_seen_at DESC);

--
-- Name: idx_supplier_product_supplier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_supplier_product_supplier ON public.supplier_product USING btree (supplier_id);

--
-- Name: idx_variant_master; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_variant_master ON public.product_variant USING btree (master_product_id);

--
-- Name: purchase_review_master_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_review_master_idx ON public.purchase_review USING btree (master_product_id);

--
-- Name: purchase_review_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_review_status_idx ON public.purchase_review USING btree (status, created_at DESC);

--
-- Name: purchase_review_supplier_offer_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchase_review_supplier_offer_idx ON public.purchase_review USING btree (supplier_offer_id);

--
-- Name: identity_match identity_match_hard_block_guard; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER identity_match_hard_block_guard BEFORE INSERT OR UPDATE ON public.identity_match FOR EACH ROW EXECUTE FUNCTION public.prevent_auto_link_hard_block();

--
-- Name: master_product master_product_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER master_product_updated_at BEFORE UPDATE ON public.master_product FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

--
-- Name: product_variant product_variant_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER product_variant_updated_at BEFORE UPDATE ON public.product_variant FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

--
-- Name: supplier_product supplier_product_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER supplier_product_updated_at BEFORE UPDATE ON public.supplier_product FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

--
-- Name: suppliers suppliers_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER suppliers_updated_at BEFORE UPDATE ON public.suppliers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

--
-- Name: identity_hard_block identity_hard_block_match_result_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identity_hard_block
    ADD CONSTRAINT identity_hard_block_match_result_id_fkey FOREIGN KEY (match_result_id) REFERENCES public.identity_match(id) ON DELETE CASCADE;

--
-- Name: market_price_observation market_price_observation_master_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_price_observation
    ADD CONSTRAINT market_price_observation_master_product_id_fkey FOREIGN KEY (master_product_id) REFERENCES public.master_product(id) ON DELETE CASCADE;

--
-- Name: market_price_observation market_price_observation_product_variant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_price_observation
    ADD CONSTRAINT market_price_observation_product_variant_id_fkey FOREIGN KEY (product_variant_id) REFERENCES public.product_variant(id) ON DELETE SET NULL;

--
-- Name: master_product master_product_origin_supplier_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_product
    ADD CONSTRAINT master_product_origin_supplier_product_id_fkey FOREIGN KEY (origin_supplier_product_id) REFERENCES public.supplier_product(id) ON DELETE SET NULL;

--
-- Name: match_evidence match_evidence_match_result_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_evidence
    ADD CONSTRAINT match_evidence_match_result_id_fkey FOREIGN KEY (match_result_id) REFERENCES public.identity_match(id) ON DELETE CASCADE;

--
-- Name: identity_match match_result_master_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identity_match
    ADD CONSTRAINT match_result_master_product_id_fkey FOREIGN KEY (master_product_id) REFERENCES public.master_product(id) ON DELETE SET NULL;

--
-- Name: identity_match match_result_supplier_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identity_match
    ADD CONSTRAINT match_result_supplier_product_id_fkey FOREIGN KEY (supplier_product_id) REFERENCES public.supplier_product(id) ON DELETE CASCADE;

--
-- Name: product_identifier product_identifier_master_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_identifier
    ADD CONSTRAINT product_identifier_master_product_id_fkey FOREIGN KEY (master_product_id) REFERENCES public.master_product(id) ON DELETE CASCADE;

--
-- Name: product_media product_media_master_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_media
    ADD CONSTRAINT product_media_master_product_id_fkey FOREIGN KEY (master_product_id) REFERENCES public.master_product(id) ON DELETE CASCADE;

--
-- Name: product_media product_media_product_variant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_media
    ADD CONSTRAINT product_media_product_variant_id_fkey FOREIGN KEY (product_variant_id) REFERENCES public.product_variant(id) ON DELETE CASCADE;

--
-- Name: product_variant product_variant_master_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variant
    ADD CONSTRAINT product_variant_master_product_id_fkey FOREIGN KEY (master_product_id) REFERENCES public.master_product(id) ON DELETE CASCADE;

--
-- Name: profit_snapshot profit_snapshot_supplier_offer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profit_snapshot
    ADD CONSTRAINT profit_snapshot_supplier_offer_id_fkey FOREIGN KEY (supplier_offer_id) REFERENCES public.supplier_offer(id) ON DELETE CASCADE;

--
-- Name: purchase_review purchase_review_master_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_review
    ADD CONSTRAINT purchase_review_master_product_id_fkey FOREIGN KEY (master_product_id) REFERENCES public.master_product(id);

--
-- Name: purchase_review purchase_review_supplier_offer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_review
    ADD CONSTRAINT purchase_review_supplier_offer_id_fkey FOREIGN KEY (supplier_offer_id) REFERENCES public.supplier_offer(id);

--
-- Name: quality_diagnosis quality_diagnosis_patrol_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quality_diagnosis
    ADD CONSTRAINT quality_diagnosis_patrol_run_id_fkey FOREIGN KEY (patrol_run_id) REFERENCES public.quality_patrol_run(id) ON DELETE CASCADE;

--
-- Name: quality_gate_result quality_gate_result_supplier_offer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quality_gate_result
    ADD CONSTRAINT quality_gate_result_supplier_offer_id_fkey FOREIGN KEY (supplier_offer_id) REFERENCES public.supplier_offer(id) ON DELETE CASCADE;

--
-- Name: supplier_offer_freshness supplier_offer_freshness_supplier_offer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_offer_freshness
    ADD CONSTRAINT supplier_offer_freshness_supplier_offer_id_fkey FOREIGN KEY (supplier_offer_id) REFERENCES public.supplier_offer(id) ON DELETE CASCADE;

--
-- Name: supplier_offer_observation supplier_offer_observation_supplier_offer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_offer_observation
    ADD CONSTRAINT supplier_offer_observation_supplier_offer_id_fkey FOREIGN KEY (supplier_offer_id) REFERENCES public.supplier_offer(id) ON DELETE CASCADE;

--
-- Name: supplier_offer supplier_offer_product_variant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_offer
    ADD CONSTRAINT supplier_offer_product_variant_id_fkey FOREIGN KEY (product_variant_id) REFERENCES public.product_variant(id) ON DELETE SET NULL;

--
-- Name: supplier_offer_snapshot supplier_offer_snapshot_supplier_offer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_offer_snapshot
    ADD CONSTRAINT supplier_offer_snapshot_supplier_offer_id_fkey FOREIGN KEY (supplier_offer_id) REFERENCES public.supplier_offer(id) ON DELETE CASCADE;

--
-- Name: supplier_offer supplier_offer_supplier_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_offer
    ADD CONSTRAINT supplier_offer_supplier_product_id_fkey FOREIGN KEY (supplier_product_id) REFERENCES public.supplier_product(id) ON DELETE CASCADE;

--
-- Name: supplier_product_identifier supplier_product_identifier_supplier_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_product_identifier
    ADD CONSTRAINT supplier_product_identifier_supplier_product_id_fkey FOREIGN KEY (supplier_product_id) REFERENCES public.supplier_product(id) ON DELETE CASCADE;

--
-- Name: supplier_product supplier_product_supplier_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier_product
    ADD CONSTRAINT supplier_product_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE CASCADE;

--
-- Name: identity_match; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.identity_match ENABLE ROW LEVEL SECURITY;

--
-- Name: ingestion_run; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ingestion_run ENABLE ROW LEVEL SECURITY;

--
-- Name: market_price_observation; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.market_price_observation ENABLE ROW LEVEL SECURITY;

--
-- Name: master_product; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.master_product ENABLE ROW LEVEL SECURITY;

--
-- Name: match_evidence; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.match_evidence ENABLE ROW LEVEL SECURITY;

--
-- Name: product_identifier; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.product_identifier ENABLE ROW LEVEL SECURITY;

--
-- Name: product_media; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.product_media ENABLE ROW LEVEL SECURITY;

--
-- Name: product_variant; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.product_variant ENABLE ROW LEVEL SECURITY;

--
-- Name: profit_snapshot; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.profit_snapshot ENABLE ROW LEVEL SECURITY;

--
-- Name: purchase_review; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.purchase_review ENABLE ROW LEVEL SECURITY;

--
-- Name: quality_diagnosis; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.quality_diagnosis ENABLE ROW LEVEL SECURITY;

--
-- Name: quality_gate_result; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.quality_gate_result ENABLE ROW LEVEL SECURITY;

--
-- Name: quality_patrol_run; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.quality_patrol_run ENABLE ROW LEVEL SECURITY;

--
-- Name: quality_run; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.quality_run ENABLE ROW LEVEL SECURITY;

--
-- Name: supplier_offer; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.supplier_offer ENABLE ROW LEVEL SECURITY;

--
-- Name: supplier_offer_snapshot; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.supplier_offer_snapshot ENABLE ROW LEVEL SECURITY;

--
-- Name: supplier_product; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.supplier_product ENABLE ROW LEVEL SECURITY;

--
-- Name: suppliers; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

--
-- Reference data seeded by migrations (deterministic order)
--

INSERT INTO public.freshness_policy (metric, max_age_seconds) VALUES ('INVENTORY', 21600);
INSERT INTO public.freshness_policy (metric, max_age_seconds) VALUES ('PRICE', 86400);
INSERT INTO public.freshness_policy (metric, max_age_seconds) VALUES ('SHIPPING', 604800);
